version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: hirable-ai-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - hirable-ai-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: hirable-ai-redis-ui
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      - redis
    networks:
      - hirable-ai-network

volumes:
  redis_data:
    driver: local

networks:
  hirable-ai-network:
    driver: bridge